### ISSUE TITLE
Add section to Audit Rules page for HumanLangMissing and link to it from rule

### ISSUE THREAD

**Issue by alice** [GoogleChrome/accessibility-developer-tools#119]
- Modify https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules
- Get the direct link to the rule using the 'link' icon which appears on the left when you hover over the heading (e.g. https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#-ax_aria_01--elements-with-aria-roles-must-use-a-valid-non-abstract-aria-role)
- Add that in to the audit rule source as its 'url' value.

**Comment by RickSBrown** [comment]
FYI I was filling in some of the blanks in the audit rules on the wiki (mainly ARIA audits) and I added an entry for AX_HTML_01. Obviously feel free to change it as much as you please.

https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#-ax_html_01--the-web-page-should-have-the-contents-human-language-indicated-in-the-markup

**Comment by alice** [comment]
Oh, that looks great! Thanks!

(Just reading through the rest of the wiki now - wow, lots of trout!)

**Comment by RickSBrown** [comment]
@chenglo I see you are assigned to this. I have been doing a lot of housekeeping on the wiki and have opened a [pull request](https://github.com/GoogleChrome/accessibility-developer-tools/pull/137) which will resolve this issue (I ensured EVERY audit rule had a URL). Hope you don't mind, let me know if you do.

**Comment by chenglo** [comment]
@RickSBrown That works for me! Thanks.

**Comment by RickSBrown** [comment]
Sweet.
PR #137 closes this.
