### ISSUE TITLE
False Negatives running in chrome browser, but not running through phantomjs

### ISSUE THREAD

**Issue by tute** [GoogleChrome/accessibility-developer-tools#126]
When we do `axs.Audit.run()` to Google.com as in https://github.com/GoogleChrome/accessibility-developer-tools/issues/125 we get a few `FAIL`s, but if we run the same script in google.com in Chrome's console we do not:

![screen shot 2014-12-23 at 4 56 14 pm](https://cloud.githubusercontent.com/assets/54260/5543604/a2e0de22-8ac4-11e4-99fd-1f0dc416a199.png)

This may be relevant and high priority for the Chrome Extension.

**Comment by ckundo** [comment]
@alice the Chrome extension is working properly after all on my machine - Adblock was interfering with ADT, everything worked after disabling adblock. @tute are you using Adblock?

**Comment by RickSBrown** [comment]
The problem appears to be in `axs.AuditRule.collectMatchingElements` in particular in the way it handles shadow DOM.

I think this assumption is wrong:

```javascript
// Descend into node:
// If it has a ShadowRoot, ignore all child elements - these will be picked
// up by the <content> or <shadow> elements. Descend straight into the
// ShadowRoot.
```

An element could have both regular DOM child elements AND shadow DOM.
When Adblock is installed the documentElement (the HTML element) has a shadowRoot - the entire DOM is therefore not audited, only the shadow DOM.

It could be as simple as commenting out the return statement on line 148 of `AuditRule.js`.

**Comment by RickSBrown** [comment]
@ckundo I fixed this in my existing pull request - sorry I wasn't sure how to create an entirely isolated pull request from my fork.

I added some unit tests but they only function when run on a platform that supports shadow dom - in other words they do nothing in the current version of phantomjs.

https://github.com/RickSBrown/accessibility-developer-tools/commit/3a3da9a013f132375f3dc89acb7e1b0623e55182

**Comment by alice** [comment]
@RickSBrown Could you pull this fix into a separate branch and create a new pull request for it?

**Comment by alice** [comment]
@RickSBrown Also, I checked, and it's not quite accurate that "An element could have both regular DOM child elements AND shadow DOM" - what's happening with AdBlock Plus is that it's inserting a shadow root containing only a `<shadow>` element, and the `<shadow>` element is hosting the rest of the content. So what actually needs to be fixed is that in this if-block https://github.com/GoogleChrome/accessibility-developer-tools/blob/master/src/js/AuditRule.js#L169 we need to check _first_ for `olderShadowRoot`, but then check for distributed nodes as per https://github.com/GoogleChrome/accessibility-developer-tools/blob/master/src/js/AuditRule.js#L157

**Comment by RickSBrown** [comment]
@alice I created a pull request but hadn't read your additional comments. I'll rework the pull request, ignore it for the moment, I'll post back here when I'm done.
