### ISSUE TITLE
Suggestions for releases

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/accessibility-developer-tools#134]
We recently published the tools to npm so developers could easily consume and build other tools on top of it rather than submoduling. The latest version in both the repo and on there is 2.6.0.

In the releases and tags section of the repo however, we last tagged a version back in early 2014 (0.0.5): https://github.com/GoogleChrome/accessibility-developer-tools/releases

In order to maintain version consistency and get into a regular release cadence, I would suggest that we:

* Bump the next release (in package.json) to 2.6.1
* Tag master with 2.6.1
* Publish 2.6.1 to npm
* Follow this process or use a tool like [npm-release](https://www.npmjs.com/package/npm-release) to automate the above steps as and when we want to cut new releases.

A target release cycle of once every 2-3 weeks would ensure the latest fixes are always available to dependents.

I would also suggest that (if possible), we try to do clean Release-page change logs every time a release is cut so it's clear to end developers what has changed.

I would be happy to help with some of this, but tagging in @alice for her thoughts here :)

**Comment by alice** [comment]
We also need to include in that process
- dist/js/axs_testing.js (for people not using Node)
- the extension.

I'm definitely interested in hearing about anything we can use to automate this, and to verify releases. @addyosmani would you have some time this week for a chat to explain how npm-release fits into the picture, and how we might be able to keep all these artifacts in sync?

**Comment by addyosmani** [comment]
@alice Absolutely. Want to find a time that works for you and we can chat? :)

**Comment by marcysutton** [comment]
So happy this is on npm :dancer:

**Comment by addyosmani** [comment]
@alice Looks like I completely forgot to bring this up the last few times we've had a chat :) Shall we try again for a vc this week or next? or just via email?

**Comment by alice** [comment]
@addyosmani I'm such a space cadet, this totally fell off my radar again. Do you have any time in the next week to chat about this? I can set something up if you're ok for me to just grab a free spot on your calendar.

**Comment by ckundo** [comment]
Looks like all of these steps are/have been taken. Great work!
