### ISSUE TITLE
ax_focus_03 "Avoid positive integer values for tabIndex" needs explanation

### ISSUE THREAD

**Issue by bkidwell** [GoogleChrome/accessibility-developer-tools#136]
The Accessibility Audit tool gave me the warning "Avoid positive integer values for tabIndex", which goes to [here in the project wiki](https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#-ax_focus_03--avoid-positive-integer-values-for-tabindex), and it's a stub. Please explain this rule. (Fix the wiki page.)

**Comment by RickSBrown** [comment]
Thanks bkidwell.

I filled in the stub on the wiki - consider that a draft until this issue is closed - I'm hoping someone else on the project (maybe @alice) will review it and make sure I have not misled anybody.

**Comment by alice** [comment]
Tweaked it a bit - @bkidwell do you want to take a look and see whether this explanation makes sense now?

**Comment by bkidwell** [comment]
Looks good to me. Thanks for clarifying.
