### ISSUE TITLE
Is there any way to integrate this library with selenium automation script ? 

### ISSUE THREAD

**Issue by ShashwatDubey** [GoogleChrome/accessibility-developer-tools#143]
I am working with selenium webdriver for functional as well as accessibility testing. And would like to integrate this library with our automation script so to get accessibility audit report on every page load.
Please suggest if there is any way to integrate/use this library with selenium webdriver. 

-Shashwat

**Comment by ckundo** [comment]
@ShashwatDubey if you're working in Ruby, you can take a look at https://github.com/casecommons/capybara-accessible. It's a rubygem that incorporates the Accessibility Developer Tools, that allows you to write scripts in Ruby and run them using Selenium webdriver or other webdrivers.

**Comment by kristapsmelderis** [comment]
I have a commit that adds instructions to readme, but Travis Build is failing for some reason and my commit is not going through.


I am trying to use Grunt to build the project and it fails on externs.js
(trying to figure out what its about).

**Comment by ShashwatDubey** [comment]
@ckundo i am working in Java and never worked in Ruby, but anyways i will try that option too. 
@kristapsmelderis Thanks for the update. Will be looking for the same. It would really help.

**Comment by alice** [comment]
It looks like this is resolved - any objections to my closing this bug?

**Comment by ShashwatDubey** [comment]
@alice yes, we can close this bug.
