### ISSUE TITLE
Enhancement: Provide a config object to AuditConfiguration constructor

### ISSUE THREAD

**Issue by loginx** [GoogleChrome/accessibility-developer-tools#164]
I think it would be nice to be able to provide a configuration payload to the `AuditConfiguration` constructor instead of creating it and then setting each option one by one.

This would allow for config payloads to be reusable when running a batch of audits.

i.e.

```javascript
var config, auditConfig, audit, report;

config = {
  scope: document.querySelector('.active'),
  showUnsupportedRulesWarning: false,
  maxResults: 1
};

auditConfig = new axs.AuditConfiguration(config);
audit = axs.Audit.run(auditConfig);
report = axs.Audit.createReport(audit);
```

**Comment by alice** [comment]
This idea :+1:
