### ISSUE TITLE
False positive AX_FOCUS_01 when control is inside shadow root.

### ISSUE THREAD

**Issue by dzhioev** [GoogleChrome/accessibility-developer-tools#171]
Here is a repro page: http://dzhioev.net:8080/shadow_focusable_obscured.html
My browser: Google Chrome	45.0.2427.7 (Official Build) dev

Audit thinks that `<button>` is obscured by `<x-foo>`, which is not true. Actually `<button>` is inside `<x-foo>`'s shadow root.
Looks like patch https://github.com/GoogleChrome/accessibility-developer-tools/compare/master...dzhioev:patch-1 solves the issue.

**Comment by alice** [comment]
Thanks for looking into this! Would you be interested in making a PR for that change?

If so, could you please add a test for the issue (presumably based on that repro page)? If you'd rather not, would it be ok if I pulled that change into my own repo to create a PR?

**Comment by dzhioev** [comment]
Sorry, I don't have time for that. Also I'm not sure that my patch is good enough (maybe `axs.utils.parentElement` should be used instead of `node.parentNode || node.host`, don't know). You can use my patch and repro page, if you want to.
