### ISSUE TITLE
AX_AUDIO_01 Stub

### ISSUE THREAD

**Issue by walshie4** [GoogleChrome/accessibility-developer-tools#175]
The [AX_AUDIO_01](https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_audio_01) audit rule is missing its code stub.  Looks like someone just forgot to fill it in. :stuck_out_tongue_winking_eye:

**Comment by jdan** [comment]
Lots of stubs in the wiki, I'm fairly certain that means the authors haven't gotten around to writing the details - not that they've forgotten.

**Comment by ckundo** [comment]
@walshie4 @jdan yep. It's on our radar to flesh those out. Thanks!
