### ISSUE TITLE
HTML noscript element should not be considered in the low contrast tests

### ISSUE THREAD

**Issue by RickSBrown** [GoogleChrome/accessibility-developer-tools#203]
`script` elements are already ignored, `noscript` should be too since there is no way to know how the content would be presented if JS was turned off.

This test should pass but currently fails:
```javascript
test("Noscript = no relevant elements", function() {
  var fixture = document.getElementById('qunit-fixture');
  var noscript = document.createElement("noscript");
  var para = noscript.appendChild(document.createElement("p"));
  para.textContent = "Please enable JS to use this app";
  para.style.backgroundColor = 'white';
  para.style.color = 'white';  // this line is optional
  fixture.appendChild(noscript);
  deepEqual(
    axs.AuditRules.getRule('lowContrastElements').run({ scope: fixture }),
    { result: axs.constants.AuditResult.NA }
  );
});
```

**Comment by alice** [comment]
I don't get the logic here. `noscript` is what is shown if JS is disabled, right? That should definitely meet contrast ratio requirements, and the code as written will check it as "probably" rendered (i.e. checking CSS styles etc) I believe.

**Comment by RickSBrown** [comment]
Now that I have to justify it here it's made me realise I do not have a strong case.
The argument in my head went something like, it's not actually part of the rendered DOM.

I'm going to close this. Doh!
