### ISSUE TITLE
publish 2.8.0 to npm

### ISSUE THREAD

**Issue by ctaymor** [GoogleChrome/accessibility-developer-tools#215]
Looks like 2.8.0 was released to github but it's not released to npm.

**Comment by RickSBrown** [comment]
If this is in relation to your comment here https://github.com/GoogleChrome/accessibility-developer-tools/issues/199#issuecomment-126097613 

I don't think 2.8.0 includes that fix...

**Comment by atomanyih** [comment]
It's not, it just came up while we were investigating. Thought someone might want to know :grin:

**Comment by jdan** [comment]
```
$ npm view accessibility-developer-tools | grep versions
  versions: [ '2.6.0', '2.7.0', '2.7.1-rc.1', '2.8.0', '2.9.0-rc.0' ],
```
