### ISSUE TITLE
tableHasAppropriateHeaders has broken behaviour for empty tables

### ISSUE THREAD

**Issue by alice** [GoogleChrome/accessibility-developer-tools#251]
https://github.com/GoogleChrome/accessibility-developer-tools/blob/master/src/audits/TableHasAppropriateHeaders.js#L27 et al assume that `rows` is non-zero length, which is not always the case. An empty table is obviously degenerate, but we shouldn't choke on it - I suggest that it pass the audit as there's no content for there to be a header for.

**Comment by alice** [comment]
@ctaymor @kennyw12 would either of you like to take a look at this?

**Comment by kennyw12** [comment]
@alice in the [WebAIM checklist](http://webaim.org/standards/508/checklist), section (g) states that a table with no header rows is a fail.

**Comment by alice** [comment]
@kennyw12 It can occur as a placeholder or some weird scripting. Obviously it is a weird case, but it shouldn't cause a JS error.

**Comment by efrenamarille** [comment]
O
On 20 Nov 2015 12:18, Alice <notifications@github.com> wrote:@kennyw12 It can occur as a placeholder or some weird scripting. Obviously it is a weird case, but it shouldn't cause a JS error.

**Comment by efrenamarille** [comment]
On 19 Nov 2015 07:13, Alice <notifications@github.com> wrote:https://github.com/GoogleChrome/accessibility-developer-tools/blob/master/src/audits/TableHasAppropriateHeaders.js#L27 et al assume that rows is non-zero length, which is not always the case. An empty table is obviously degenerate, but we shouldn't choke on it - I suggest that it pass the audit as there's no content for there to be a header for.

**Comment by kennyw12** [comment]
I'll make a PR to fix the JS error and fail the case.

**Comment by alice** [comment]
I don't think it's appropriate to fail the case. The table won't be exposed
as a data table in most browsers.

**Comment by kennyw12** [comment]
After reading more about tables, I agree.

**Comment by kennyw12** [comment]
I'm not sure how a screen reader will handle it. 

@atomanyih what do you think?

**Comment by dylanb** [comment]
@kennyw12 - screen readers will ignore the empty table. @alice is correct, while this is not a best practice in terms of HTML usage, it should not cause accessibility problems in reality.
