### ISSUE TITLE
Exception thrown when testing tooltips without aria-describedby

### ISSUE THREAD

**Issue by notwaldorf** [GoogleChrome/accessibility-developer-tools#269]
This line of code (`axs_testing.js:2169`, if that helps) throws an exception
```
return 0 === axs.utils.getAriaIdReferrers(a, "aria-describedby").length;
```
because `axs.utils.getAriaIdReferrers(a, "aria-describedby")` is `null`

**Comment by alice** [comment]
https://github.com/GoogleChrome/accessibility-developer-tools/blob/master/src/audits/RoleTooltipRequiresDescribedBy.js#L33 is the original line of code. This should check for null. Also, https://github.com/GoogleChrome/accessibility-developer-tools/blob/812ad9cc6170d7655adcd62707d1e75d3c99a12a/src/js/AccessibilityUtils.js#L1004 should probably be explicitly annotated as a nullable return value.

**Comment by alice** [comment]
Additionally, that rule should be a `WARNING` severity, since the advice in http://www.w3.org/WAI/PF/aria/roles#tooltip is a SHOULD rather than a MUST.
