### ISSUE TITLE
AX_TEXT_01 false positive when `<input>` element contains a `placeholder` attr

### ISSUE THREAD

**Issue by rnicholus** [GoogleChrome/accessibility-developer-tools#271]
From the audit:

<img width="575" alt="screen shot 2016-01-27 at 10 03 28 am" src="https://cloud.githubusercontent.com/assets/593312/12602618/441e963c-c4dd-11e5-8049-f0139cfe628d.png">

The [explanation of this rule](https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_text_01) mentions that a `placeholder` attribute is a valid fix:

> 
```html
<!-- Good: Using placeholder text -->
<input placeholder="Enter your address">
```

As you can see from the audit output, the element does indeed have a `placeholder` attribute.

**Comment by jdan** [comment]
Hey @rnicholus,

Sorry you ran into this one! Placeholders unfortunately won't reliably work as labels, and we'll need to re-word the wiki to correct the error there (the audit is working as expected).

More [explanation of placeholders as labels](https://www.w3.org/WAI/tutorials/forms/instructions/#placeholder-text) can be found here:

> While placeholder text provides important guidance for many users, **placeholder text is not a replacement for labels**. Assistive technologies, such as screen readers, do not treat placeholder text as labels. Moreover, at the time of writing this tutorial, placeholder text is not broadly supported across assistive technologies and not displayed in older web browsers.

Thanks for bringing this to our attention, and once again my apologies for the confusion here.

**Comment by jdan** [comment]
Here are the changes to the wiki:

https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules/_compare/671f598ef36098fb1dc91e669caf00b4da0af9ff...b212de272832768d3f88c4058a7238297a81a893
