### ISSUE TITLE
How does one Restrict the scope of the Audit? Not clear from this Wiki.

### ISSUE THREAD

**Issue by ssjjcc** [GoogleChrome/accessibility-developer-tools#290]
This is a dumb question, but looking at the README, it mentions that you can restrict the scope of the entire audit to a subsection of the page. It says that to do this, all you do is redefine the configuration like this:

var configuration = new axs.AuditConfiguration();
configuration.scope = document.querySelector('main');  // or however you wish to choose your scope element
axs.Audit.run(configuration);

However, I couldn't understand from the README as to where you actually do this. In the tools/runner/audit.js file? In the dist/js/axs_testing file? If anyone has experience with this, please let me know. Thanks!

**Comment by jdan** [comment]
Heya @ssjjcc,

Typically you'll use this library by injecting `axs_testing.js` into a page, which exposes a global `axs` object. After this you'll call `axs.Audit.run()` on the page, so around here is where you'll specify a custom configuration.

[Here's a sample implementation](https://github.com/addyosmani/a11y/blob/master/audits.js#L54-L55). Does that clear things up?

**Comment by ssjjcc** [comment]
Sorry, finger slipped over the close issue button there.

Yes, that makes a lot of scene. Looks like most of the problem revolved around not including the needed dependencies, like 'system' and 'webpage'. Thanks @jdan! With the audit now being restricted, that does open up my second question..

I'm able to simply put html, head, or body in the querySelector. Example:
configuration.scope = document.querySelector('main'); .However, these are one time instance html tags. How do I put in unique tags so I can test them, like <div id=banner> or <div class=mobile-nav>?

**Comment by Timetrax** [comment]
I can't understand what you read -
I speak gearman, and i only had a smartphone.
Sabine Stein
Am 30.06.2016 19:57 schrieb "Scott Christensen" <notifications@github.com>:

**Comment by ssjjcc** [comment]
Oh, sorry! I just had a question about restricting the Audit. I wanted to know what you are supposed to put into `document.querySelector( );` so that the Audit will run inside of unique html tags?

**Comment by jdan** [comment]
@ssjjcc Great question :)

The text passed to `document.querySelector` represents a [CSS query selector](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Getting_Started/Selectors), the types of rules you would normally enter into a stylesheet to target specific items.

To point to something by id, you prefix the string with a hash (in your case, `"#banner"`). For classes, you use a period (for example, `".mobile-nav"`).

Does that make sense?

**Comment by ssjjcc** [comment]
Yep, that's exactly the info I needed and now it works like a dream. I'll go ahead and close this issue for real because you answered all of my questions regarding Audit restriction. Again, thanks a bunch!
