### ISSUE TITLE
The js library reports only a subset of accessibility errors/ warnings 

### ISSUE THREAD

**Issue by prashant4github** [GoogleChrome/accessibility-developer-tools#331]
Hi,
I tried to utilize the accessibility JS library (https://raw.github.com/GoogleChrome/accessibility-developer-tools/stable/dist/js/axs_testing.js) to check my webpage for "accessibility errors". The js library did work but returned a limited number of error/ warning details in comparison to errors reported by "Accessibility developer tool plugin for Chrome browser". I assume, this happened because the online JS library (https://raw.github.com/GoogleChrome/accessibility-developer-tools/stable/dist/js/axs_testing.js) is not up to date. Can an up to date version of this js libraray be provided to us? Please let me know.
Thanks,
Prashant

**Comment by schindld** [comment]
If you diff [v2.11.0](https://raw.githubusercontent.com/GoogleChrome/accessibility-developer-tools/v2.11.0/dist/js/axs_testing.js) and [v2.12.0](https://raw.githubusercontent.com/GoogleChrome/accessibility-developer-tools/v2.12.0/dist/js/axs_testing.js), you will see that almost 20 rules were removed at the end of the file. You can copy/paste them back in, and it will work - running all 28 rules for you. No idea why the rules were removed though.

**Comment by jbanks77** [comment]
Wow, thank you, my nephew was playing his game on my laptop, maybe I left it exposed, I’m sry


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by schindld** [comment]
@jbanks77 you might want to delete your comment, as it seems you didn't realize you were posting in this thread: https://github.com/GoogleChrome/accessibility-developer-tools/issues/331.

@prashant4github, just use v2.11.0 for now, until v2.12.0 becomes stable.

**Comment by prashant4github** [comment]
@schindld 
Thanks for the update. I will use v2.11.0 for now. :)
