### ISSUE TITLE
AX_FOCUS_01 Shouldn't anchor elements visible onFocus be excluded from this warning.

### ISSUE THREAD

**Issue by hexalys** [GoogleChrome/accessibility-developer-tools#65]
It's me again with another link focus related conundrum:

Sites get the warning "These elements are focusable but either invisible or obscured by another element" on &lt;a&gt; elements such as skip links or menubar links, even if those focusable elements are actually shown via specific CSS a:focus rules.

Shouldn't you check the onFocus visibility of such elements dynamically first, before considering it invisible or obscured?

If the element is purposely shown with a:focus, it is technically visible by a keyboard user using the tab key, as well as a mouse user. Properly designed navigation bars with pull down submenus made visible onFocus is a good use case here.

It would also help developers determining which links are not visible by sightseeing users vs those which are purposely shown to both via a:focus rules, and assess whether the ones receiving a warning shall be tagged as aria-hidden or not.

PS: As added enforcement to verify that those links are in fact shown, you could perhaps check the contrast ratio while onFocus. If the contrast ratio fail in both states, report it as insufficiently visible or something like that?

**Comment by GaryJones** [comment]
This issue is marked as closed, but skip links are still getting flagged:

![screenshot 2017-02-10 03 18 53](https://cloud.githubusercontent.com/assets/88371/22812924/ab1921e4-ef3f-11e6-89d8-0a7df1bd9e2f.png)
